[colors]
background = '#070b14'
foreground = '#e6edf7'

cursor_bg = '#ff4e66'
cursor_fg = '#070b14'
cursor_border = '#ff4e66'

selection_bg = '#3a1620'
selection_fg = '#e6edf7'

ansi = ['#0b0f1a', '#ff3c3f', '#76ff4e', '#ffd83c', '#f62e46', '#760010', '#ff4e66', '#ffe9ec']
brights = ['#a59496', '#ff7a7c', '#9fff83', '#ffe683', '#ff687c', '#ff8393', '#ffafba', '#fff6f7']
